version: '3.9'

# Logging settings defaults we can just append to any service config.
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 2000m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  node-exporter:
    image: prom/node-exporter:latest
    user: root
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9100
    <<: *logging

  cadvisor:
    restart: unless-stopped
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /etc/machine-id:/etc/machine-id:ro
    command:
      - --docker_only
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8080
    <<: *logging
