version: '3.9'

# Logging settings defaults we can just append to any service config.
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 2000m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  mimir-lb:
    image: nginx:latest
    volumes:
      - $PWD/mimir-lb-nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "mimir-lb-a"
      - "mimir-lb-b"
      - "mimir-lb-c"
    hostname: mimir-lb
    ports:
      - 9010:9010
    deploy:
      mode: replicated
      replicas: 1
    <<: *logging

  mimir-lb-a:
    image: grafana/mimir:latest
    volumes:
      - mimir-lb-a-data:/data
      - $PWD/mimir-lb-config.yml:/etc/mimir-template.yml
      - $PWD/mimir-entrypoint.sh:/etc/mimir-entrypoint.sh
    entrypoint: [ "sh", "/etc/mimir-entrypoint.sh" ]
    hostname: mimir-lb-a
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: ["node.role == worker"]
    <<: *logging

  mimir-lb-b:
    image: grafana/mimir:latest
    volumes:
      - mimir-lb-b-data:/data
      - $PWD/mimir-lb-config.yml:/etc/mimir-template.yml
      - $PWD/mimir-entrypoint.sh:/etc/mimir-entrypoint.sh
    entrypoint: [ "sh", "/etc/mimir-entrypoint.sh" ]
    hostname: mimir-lb-b
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: ["node.role == worker"]
    <<: *logging

  mimir-lb-c:
    image: grafana/mimir:latest
    volumes:
      - mimir-lb-c-data:/data
      - $PWD/mimir-lb-config.yml:/etc/mimir-template.yml
      - $PWD/mimir-entrypoint.sh:/etc/mimir-entrypoint.sh
    entrypoint: [ "sh", "/etc/mimir-entrypoint.sh" ]
    hostname: mimir-lb-c
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: ["node.role == worker"]
    <<: *logging

volumes:
  mimir-lb-a-data:
  mimir-lb-b-data:
  mimir-lb-c-data:

