version: '3.9'

# Logging settings defaults we can just append to any service config.
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 2000m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

volumes:
  minio_data: {}

services:
  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    hostname: minio
    entrypoint: ["/usr/bin/sh", "-c", "mkdir -p /data/mimir && minio server --quiet /data --console-address \":9001\""]
    environment:
      - MINIO_ROOT_USER=myminio
      - MINIO_ROOT_PASSWORD=mypassword
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
    <<: *logging
