global:
  scrape_interval:     15s
  evaluation_interval: 15s

remote_write:
  - url: http://mimir-lb:9010/api/v1/push
    headers:
      "X-Scope-OrgID": "primary"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # Discover targets using labels on containers.
  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
       - source_labels: [__meta_docker_container_label_metrics_scrape]
         regex: true
         action: keep

       - source_labels: [__meta_docker_container_label_com_docker_swarm_service_name]
         target_label: job

       - source_labels: [__meta_docker_container_name]
         regex: /(.*)
         replacement: $1
         target_label: container_name

       - source_labels: [__meta_docker_container_label_com_docker_stack_namespace]
         target_label: project

       - action: replace
         regex: (.+)
         source_labels:
         - __meta_docker_container_label_metrics_path
         target_label: __metrics_path__
         
       - action: replace
         regex: ([^:]+)(?::\d+)?;(\d+)
         replacement: $1:$2
         source_labels:
         - __address__
         - __meta_docker_container_label_metrics_port
         target_label: __address__
